const notes = ["!Testing and Debugging",
"Three types of errors",
"System error – error with user’s external system ",
"Programmer error – incorrect syntax or faulty logic ",
"User error – data inputs invalid from user ",
"Little control over system error, and efforts should be focused on minimizing programming errors ",
"Exceptions are errors that return with a value to define the error, such as ReferenceError, meaning the term isn’t defined ",
"Stack trace are the path of which the error occurred, such as error occurred in first function, then from main which called first function, which main is located in main.js, indicated the lines at each was called ",
"Warning, error in program that won’t cause it to crash and continue running, not all browsers support warnings ",
"Using strict mode, which will cause more exceptions and warnings to aide in writing proper code, by using ‘use strict’; at the top of JS file ",
"Strict mode can also be within functions to only run within the local function scope ",
"Linting tools are external tools to test quality of JS code, can be installed in text editors or through npm. Several linting tools: JS Lint,JS Hint and ES Lint ",
"Lint tests are not 100% guaranteed correct but a step in the right direction ",
"Feature detection, use if statement to check if it exists before assuming it’ll work ",
"Alerts can be used to debug in browser, as blocks code until the user presses ‘Ok’ ",
"The debugger keyword can be used to add breakpoints in the browsers Firefox, Edge, Chrome, Safari, ensure to remove debugger code in final product ",
"Error can be made into an object to have custom errors ",
"7 types of specific errors ",
"EvalError: only kept for backwards comp. used for eval() function ",
"RangeError: value is outside of acceptable values, ex. Indexing value outside of array length ",
"ReferenceError: calling object that doesn’t exist ",
"SyntaxError: occurs when syntax error ",
"TypeError: error with type of value, using String method on int ",
"URIError: issue with encoding or decoding URI ",
"InteralError: issue with JS engine, most common cause is too many recursion calls ",
"Try, catch, finally can be used to catch errors safely while throwing back helpful errors ",
"External software such as Jest can be used to test functions and their results through npm "];

export default notes;
